#ifndef RADIOBTNLABLE_GLOBAL_H
#define RADIOBTNLABLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RADIOBTNLABLE_LIBRARY)
#  define RADIOBTNLABLE_EXPORT Q_DECL_EXPORT
#else
#  define RADIOBTNLABLE_EXPORT Q_DECL_IMPORT
#endif

#endif // RADIOBTNLABLE_GLOBAL_H
